### ISSUE TITLE
Kubernetes dashbord for pods/nodes hardcode the cluster name

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#17]
Hi,

I'm using this with a kubernetes cluster. In signalfx, when I see the cluster dashboard, it shows fine all the info (active containers, nodes, etc.). But when I go to the kubernetes nodes dashboard or kubernetes pods dashboard, it shows everything with 0.

This is because these dashboards has a cluster name in the properties is hardcoded with "cluster:localTest". If I remove (or add the proper cluster), not dashboard seems to be fine.

Can you please fix this? :)

**Comment by beccatortell** [comment]
We certainly can. Looking into it now.

**Comment by rata** [comment]
On Tue, Apr 05, 2016 at 08:36:02AM -0700, beccatortell wrote:

> We certainly can. Looking into it now. 

Thanks! Let me know if I can help you with testing or something, but it was
working when I removed the hardcoded cluster :)

**Comment by beccatortell** [comment]
Thanks, that was exactly the problem. I've removed that inappropriate filter and have pushed the change. An update should appear within the hour. Thanks again for reporting the issue!

**Comment by beccatortell** [comment]
We'd really appreciate your feedback on the integration once you've had a chance to use it. Could you please let me know the best way to get in touch with you, and which SignalFx account you're associated with?

**Comment by rata** [comment]
Sure, it will be great! I haven't used much the integration yet, but I do have some feedback. You can contact me at rodrigo.campos@restorando.com. Thanks a lot! :)

**Comment by rata** [comment]
@beccatortell Oh, and I can confirm it works now. Sorry, I forgot to tell :)

**Comment by beccatortell** [comment]
Great! Thanks.
