### ISSUE TITLE
% Memory Used per Container has a negative value

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#20]
% Memory Used per Container in a pod, shows a negative value. I think this only happens for pods that do not specify a limit, as with some kubernetes container at least it shows positive numbers.

But, for example, for the pod created in the cadvisor-signalfx RC, this number is negative too.

**Comment by beccatortell** [comment]
Thanks for reporting. We will look into this and get back to you.

**Comment by rata** [comment]
This seems fixed now, closing! :)
