### ISSUE TITLE
Not report all metrics

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#21]
Hi,

I'd like to have the possibility to not report all the metrics for all the containers in all pods. There is some information that is not so useful and we would like to have the option to avoid some points and save some money.

We have some nginx containers on several pods that we usually don't need info from (just a proxy for the real container, and to serve some static assets). Is it possible to stop reporting info for some containers in a pod? Or any way to have some granularity on the datapoints to report?

**Comment by beccatortell** [comment]
Hi there. For a container that you don't need to monitor in detail, would you still want it to be included in a list of all running containers or just not appear at all?

**Comment by rata** [comment]
On Fri, Apr 08, 2016 at 11:21:04AM -0700, beccatortell wrote:

> Hi there. For a container that you don't need to monitor in detail, would you
> still want it to be included in a list of all running containers or just not
> appear at all?

It doesn't make a big difference, I think. If they are shown, it's nice. But not
a deal breaker nor anything, as we want to not have metrics about them :)

**Comment by rata** [comment]
I'm not sure this is a big deal anymore, changing the frequency we can regulate the data points sent and we are happy with the frequency (for now at least). Closing!
