### ISSUE TITLE
Easy way to see active pods of a deployment

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#22]
Hi,

When we do a deployment, the old pods are still shown and it is not easy to see only the ones that are active now.

The  "NodeServiceRefreshRate" is "5m" and after 20 minutes of the deploy, all the pods (the one that do not exist anymore) are shown in the "pods" dashboard, for example.

Is there something to tune or some way to easily view the active pods of a deployments (or pods with active containers only) or something? Is it planned? :)

**Comment by beccatortell** [comment]
Hi there. After a deployment, all the pods are destroyed and re-created with new names, correct? About how often does this happen in your cluster? 

Does this relate to your other issue regarding pod labels? Would it make more sense for you to see status by label rather than individual pod name? 

Thanks!

**Comment by rata** [comment]
On Fri, Apr 08, 2016 at 11:14:35AM -0700, beccatortell wrote:

> Hi there. After a deployment, all the pods are destroyed and re-created with
> new names, correct? About how often does this happen in your cluster? 

Correct. We are still testing kubernetes, but we deploy several times a day in
our current infra.

> Does this relate to your other issue regarding pod labels? Would it make more
> sense for you to see status by label rather than individual pod name? 

It is nice to have a way to see the labels. As we have not yet migrated
everything to kubernetes, we are not sure how we will use the labels. But having
some way to see them, is nice.

But we want to see the pods of a deployment, because maybe we need to connect,
etc. Currently, the pods of the old deploy are shown there for at least ~30
minutes and is confusing when trying to find the active pods. This is what I
want to solve, not related to labels

**Comment by rata** [comment]
Using the new "container name" and "kubernetes_pod_name:<pod-prefix>*" shows the active now. Closing this!
