### ISSUE TITLE
Show kubernetes labels

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#23]
Hi,

Is there any plan to show or somehow integrate the kubernetes labels for pods in the signalfx interface?

**Comment by beccatortell** [comment]
Hi there. Can you tell me more about how you'd like to use pod labels within SignalFx?

**Comment by rata** [comment]
On Fri, Apr 08, 2016 at 11:10:19AM -0700, beccatortell wrote:

> Hi there. Can you tell me more about how you'd like to use pod labels within SignalFx? 

I have't really thought about it. But definitely a way to see them is nice. I
can try to think about it and give more specific feedback next week. We still
don't use kubernetes in production, so we are not sure what is the most useful
way to visualize labels yet

**Comment by rata** [comment]
Maybe as a dimension. It will be nice to be able to use them as the selector in ReplicaSets (that is more general than selectors on RC). And see all the labels of a particular pod, too.

**Comment by rata** [comment]
I'll reopen if I come up with a good use case for this. I'm not sure how to use them now, and we have been using signalfx to monitor our k8s cluster for a while, with no problem and was helpful to monitor production services too! :)
