### ISSUE TITLE
See the container RSS mem usage

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#27]
The `container_memory_usage_bytes` is not the RSS size, but the VSZ size. This is not useful, as that mem is not allocated nor in use. What is in use, actually, is the RSS.

The  `container_memory_working_set_bytes` graph something, but doesn't seem to be RSS in the case of our nginx container in a pod (has several containers).

For example, in the nginx container:

```
# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         9  0.2  0.0  20240  3020 ?        Ss   14:40   0:00 bash
root        13  0.0  0.0  17496  2076 ?        R+   14:40   0:00  \_ ps faux
root         1  0.0  0.1  91428  7900 ?        Ss   Jun16   0:00 nginx: master p
www-data     7  0.0  0.0  92096  4772 ?        S    Jun16   1:23 nginx: worker p
www-data     8  0.0  0.0  92100  4780 ?        S    Jun16   1:21 nginx: worker p
```

But signalfx says that the `container_memory_working_set_bytes` for the nginx container in that pod in that namespace (i.e. applying all the filters to show only that) shows that the usage is 40MB.

Am I missing something?

**Comment by dgriff-tools** [comment]
Hi Rata,

Sorry for the delay in response.

What is the SignalFx value for the container_memory_usage_bytes for the nginx example?
I'll look at both metrics using nginx in container and see if I get same results.

**Comment by rata** [comment]
On Wed, Jun 22, 2016 at 03:50:47PM -0700, Drew Griffin wrote:

> Hi Rata,
> 
> Sorry for the delay in response.
> 
> What is the SignalFx value for the container_memory_usage_bytes for the nginx example?

It's more than 50 MB. While the RSS is ~8MB for the master and ~5MB for each
fork (there are only 2).

> I'll look at both metrics using nginx in container and see if I get same results.

Probably doesn't have to be nginx, just any process with small RSS (and probably
will help if the VSZ is larger)

Thanks a lot,
Rodrigo

**Comment by dgriff-tools** [comment]
Hi Rata,

I did a basic test to compare the metrics collectd by the cadvisor integration.
Deploy nginx in k8s cluster amd the data looks correct in SignalFx.

## 

In SignalFx 
nginx container shows 7,806,976 for container_memory_usage_bytes in chart without any analytics applied

On my k8s master
kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
my-nginx-3800858182-gmgtg   1/1       Running   0          33d

On the node running container

cd /sys/fs/cgroup/memory/system.slice/docker-a35da4c985cb705baf6754f7e0d22376e538fb3f440cda59474aeebef0063b50.scope

cat memory.usage_in_bytes
7806976

cat memory.stat
cache 6406144
rss 1400832
...

It looks like memory.usage_in_bytes = cache + rss

Using same steps I did, compare the docker memory usage between your container and the SignalFx values.
If these values are different we can go look deeper.

Drew

**Comment by rata** [comment]
@dgriff-tools oh, sorry, I read this and forgot to answer. It seems fine then. Sorry I forgot about cached :-/
I close this for now, if I find something else I'll re-open.

Thanks again!
