### ISSUE TITLE
Tweaking metrics being sent

### ISSUE THREAD

**Issue by jbarreneche** [signalfx/cadvisor-integration#30]
Hi! 
We were looking at the number of DP we send and found that the integration with kubernetes is much more verbose that what we would like (compared with deploying in hosts we are sending a lot more DP).

The first culprit is: `container_tasks_state`. It sends 5 metrics per container (which in our case are always zero. Is that a bug on our side? Is it working for you? let me know if you want me to open a separated issue about this). We would like to be able to disable metrics that we don't find useful.

The second case is metrics by namespace: kube-system. Could we change the granularity by namespace? Eg. we would like non-production namespace having less granularity and in some cases to be completely ignored (like the kube-system namespace)

The third thing we found (I think it's a bit trickier) most of our pods come with 1 or 2 other containers that do very small and not so important tasks and we would like to exclude (at least some) of the metrics that this integration reports for this containers.

Could some of these cases be considered or should we fork this integration?

We are using kubernetes 1.2, and the latest image of cadvisor-integration.

**Comment by beccatortell** [comment]
Hi there,

Thanks for the questions. We'll take a look and verify the behavior of container_tasks_state. As for your requests it sounds like you would like this agent to be modified in two ways: 
1. To use a more curated list of metrics than what it sends currently. We have previously discussed defaulting to a smaller set of metrics in the future.
2. To have the option to filter the namespaces and containers (and pods?) that the agent will report on. We hadn't previously considered this feature, but it's a reasonable request. 

This integration is a high priority for us, but there are a few items ahead of it on our roadmap. If you were to develop these changes on your end in the meantime, we would certainly be happy to work with you on a pull request. 

Best,
RT

**Comment by jbarreneche** [comment]
We would like to start working (although, we don't have a lot of time to dedicate and it's not our top priority, so I can't promise when there will be a first PR), how do you imagine doing these configurations (environment variables, mounting a config map, other?)?

What type of granularity would be good for the metrics? Individual metric whitelist/blacklist?, coarse groups whitelisting/blacklisting (eg. container_cpu__, container_fs__), other?

Same for namespaces. Whitelist or blacklist or both?

(we are open for any alternative, we would like to avoid rework and having to change our config all the time :P)

**Comment by dgriff-tools** [comment]
Hi Juan,

A variation of the approach you mentioned could be to allow matching of metric names and/or dimension values based on regular expressions.
This adds the extra control to send datapoints based on either individual metric names or for groups.
An example whitelist configuration might look like:
{ "match" : [ { "metric_name" : "^container_cpu_utilization$", "dimension_name" : "^kubernetes_namespace$", "dimension_value" : "prod.*" }, { "metric_name" : "^machine_cpu_cores$" } ] }
Where in example case you have limited sent datapoints to only (all machine_cpu_core metrics and only container_cpu_utilization metrics that are on any prod namespace).
Then maybe add the whitelist as a multi-line environment variable to the cadvisor pod spec.

Does this approach provide the flexibility you are looking for?

**Comment by jbarreneche** [comment]
Yes, it looks pretty flexible to me. As soon as we have some time we will try to give it a shot. 
Thanks!
